backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true # For local testing
media_folder: public/img
public_folder: img
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, de, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: de
collections:
  - name: "pages"
    label: "Pages"
    # same as the top level, but all fields are optional and defaults to the top level
    # can also be a boolean to accept the top level defaults
    i18n: true
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - {
              label: "Publish Date",
              name: "date",
              widget: "datetime",
              i18n: duplicate,
            }
          - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "projects"
    title: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          i18n: duplicate,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
          tagname: "",
          i18n: duplicate,
        }
      - {
          label: "Gallery",
          name: "galleryImages",
          widget: "list",
          summary: "{{fields.image}}",
          i18n: duplicate,
          field: { label: Image, name: image, widget: image },
        }
