backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# local_backend: true # For local testing
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    files:
    - label: "Holzdschungel"
      name: "1-holzdschungel"
      file: "content/projects/1-holzdschungel.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - { label: "Cover Image", name: "coverImage", widget: "image", required: false, tagname: "" }
        - { label: "Gallery",
            name: "galleryImages",
            widget: "list",
            summary: '{{fields.image}}',
            field: {label: Image, name: image, widget: image} }